using UnityEngine;
using System.Collections;
using System.IO.Ports;
using UnityEngine.UI;

public class ExtensiePicior : MonoBehaviour
{
    //serial port connection for when code needs to be tested through wire connection
    SerialPort data_stream_angles = new SerialPort("/dev/cu.usbserial-1120", 115200);
    public int myExtension;
    public int myAbduction;
    public string receivedAngle;
    public float speedOfExtension = 30f;
    public Transform patela;
    public Vector3 target;
    
    //not needed for wireless communication
    void Start()
    {
        data_stream_angles.Open();
        InvokeRepeating("Extension_Readings", 0f, 0.001f);
        
    }

    void Update()
    {
        //cod used for testing
        // string[] dataForExtending = Extension_Readings();
        // int recv_Angle_x = Mathf.RoundToInt(float.Parse(dataForExtending[0]));
        // int recv_Angle_y = Mathf.RoundToInt(float.Parse(dataForExtending[1]));
        // target = new Vector3(0, 0, recv_Angle_x);

        target = new Vector3(myAbduction,0,myExtension);

        //the center of rotation rotates based on the position given by "target" vector
        patela.transform.eulerAngles = target;
    }
    string[] Extension_Readings() {

        receivedAngle = data_stream_angles.ReadLine();
        string[] datas_angles = receivedAngle.Split(",");

        return datas_angles;
    }

    //these are the 2 functions that get information from 
    //javascript code in index.html file generated by unity in build folders
    //but that we altered to our purposes
    public void setExtension(string nr)
    {
        //System.Globalization.CultureInfo.InvariantCulture this is for keeping the same formatting
        //no matter the location of the project - i.e 1.20, decimal separator can be either . or , depending 
        //on the location
        myExtension = Mathf.RoundToInt(float.Parse(nr, System.Globalization.CultureInfo.InvariantCulture));
        //Debug.Log("Received Pitch from JS: " + nr);
    }

    public void setAbduction(string nr){
        
        myAbduction = Mathf.RoundToInt(float.Parse(nr,System.Globalization.CultureInfo.InvariantCulture));
        //Debug.Log("Received Roll from JS: " + nr);
    }

}
